### ISSUE TITLE
Issues with latest three.js Version

### ISSUE THREAD

**Issue by laooola** [prolincur/three-dxf-loader#2]
I was looking for a capable dxf loader for three.js and stumbled upon your implementation. Unfortunately, the loader does not work with the latest version of three.js (0.133.0). Extending three.js like this https://github.com/prolincur/three-dxf-loader/blob/8b54ffba4e0df9f73bcef9c566ee206d5d4fa3cc/src/Loader.js#L35 does not work anymore and causes an error - looks like the object is sealed and therefore not extendable.

I'd love to see a fix for this issue, otherwise I won't be able to keep my dependencies up to date. Happy to help if you need further information ;)

**Comment by sonisourabh** [comment]
@laooola The reported should have gone in newer version. 

However, I think it's not sufficient for three.js (0.133.0) usage. The said version of three.js does not support THREE.Geometry any more. It's deprecated to https://github.com/mrdoob/three.js/blob/master/examples/jsm/deprecated/Geometry.js

More changes are needed in the library to support this. Presently, I do not have enough time to make these changes. In case you want to volunteer, please feel free to raise a Pull Request.

**Comment by sonisourabh** [comment]
Keeping it open!

**Comment by deethee** [comment]
What is the latest supported three version?

**Comment by sonisourabh** [comment]
> What is the latest supported three version?

Up to r124 version where THREE.Geometry is not removed.

**Comment by deethee** [comment]
Is this a bigger change? Are there working alternatives?

**Comment by sonisourabh** [comment]
The library made compatible with three.js r136 lately.
