### ISSUE TITLE
TypeError: e.XHRLoader is not a constructor

### ISSUE THREAD

**Issue by NeluQi** [prolincur/three-dxf-loader#5]
![image](https://user-images.githubusercontent.com/16963395/218795045-0d56d885-3e32-45e0-835f-0ea4d8f3111a.png)

**Comment by sonisourabh** [comment]
@NeluQi which three.js version are you using?

**Comment by NeluQi** [comment]
I use 0.148.0

"three": "^0.148.0"

"three-mesh-bvh": "0.5.19"

**Comment by vyvu99** [comment]
@sonisourabh can I make PR for this?

**Comment by sonisourabh** [comment]
@vnvyvu Sure. That will be a big help.
