### ISSUE TITLE
is it possible to Extrude?

### ISSUE THREAD

**Issue by vasco3** [prolincur/three-dxf-loader#8]
I would like to extrude a 2D geometry. How could I achieve this?

**Comment by sonisourabh** [comment]
@vasco3 Yes, it's possible to extrude the 2D geometry using three.js. Refer the documentation of the same here: https://threejs.org/docs/#api/en/geometries/ExtrudeGeometry

**Comment by vasco3** [comment]
@sonisourabh nice, I managed to extrude the DXF entities.
Do you know if it is possible to apply boolean operations? I would like to subtract some holes to the shape
