### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'sphere.center')

### ISSUE THREAD

**Issue by vasco3** [prolincur/three-dxf-loader#9]
I'm running this with react-three-fiber. Loading a dxf.

**Comment by sonisourabh** [comment]
@vasco3  can you share the sample code to replicate the problem and version number of react-three-fiber and three you are using

**Comment by vasco3** [comment]
@sonisourabh 

dependencies

- "three": "^0.151.3",
- "three-stdlib": "^2.21.8"
- "three-dxf-loader": "^3.2.0",
- "react": "18.2.0",
- "@react-three/fiber": "^8.12.2",


This is the DXF, opens fine in LibreCAD
<img width="543" alt="image" src="https://user-images.githubusercontent.com/804301/233577276-675bedfe-b318-4dc3-b0c2-37e72e488466.png">

```
import { DXFLoader } from "three-dxf-loader";
import { Canvas, useLoader } from "@react-three/fiber";

// component
function DxfTest() {
  try {
    let dxf = useLoader(DXFLoader, "/3d/marco43.dxf");
    console.log("🚀 ~ file: Viewer.mjs:203 ~ Viewer ~ dxf:", dxf);
    return (
      <mesh
        name={"test dxf"}
        geometry={dxf.entities[1]}
        scale-z={1000}
        castShadow
        receiveShadow
      >
        <meshBasicMaterial color="#333" />
      </mesh>
    );
  } catch (error) {
    console.log("🚀 ~ file: Viewer.mjs:205 ~ Viewer ~ error:", error);
    return null;
  }
}
```
Console.log shows the contents of the loaded dxf 
<img width="989" alt="image" src="https://user-images.githubusercontent.com/804301/233578071-64e89f82-7762-468f-bca8-5c53e1ae72a3.png">


I insert that component in a Canvas within a Suspense
<img width="583" alt="image" src="https://user-images.githubusercontent.com/804301/233576863-e76d5b7b-e508-4c9f-b57a-5f7d3a02066e.png">

but the render throws this error in Safari
<img width="525" alt="image" src="https://user-images.githubusercontent.com/804301/233578211-149d42ff-c7e3-45a7-b9ba-adbebc2b0ab0.png">


The same in Chrome
<img width="928" alt="image" src="https://user-images.githubusercontent.com/804301/233578765-f77341bd-8fef-4418-afda-f254cb936e6a.png">

**Comment by vasco3** [comment]
Actually I got it to work by replacing `mesh` with `<primitive object={dxf.entities[0]} />`
